language: csharp
solution: "./CosmosDbRepository.sln"
install:
        - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./CosmosDbRepository.sln
        - sudo apt-get install nunit-console
script:
        - xbuild ./CosmosDbRepository.sln
        - nunit-console ./test/CosmosDbRepositoryTest/bin/Debug/netcoreapp2.2/CosmosDbRepositoryTest.dll
