# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts
name: 1.1$(rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  condition: succeeded()
  inputs:
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    command: test
    publishTestResults: true

#- task: DeleteFiles@1
#  displayName: Delete files Nuget Packages created during tests
#  inputs:
#    SourceFolder: 'src/'
#    Contents: '**/*.nupkg;**/*.snupkg'
#  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
- task: NuGetToolInstaller@0
  inputs:
    checkLatest: true # Optional
    
- task: DotNetCoreCLI@2
  displayName: 'Build All Projects (master)'
  inputs:
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget'
    packagesToPush: 'src/**/*.nupkg;src/**/*.snupkg'
    allowPackageConflicts: true
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
